apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app.kubernetes.io/name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
    spec:
      containers:
        - name: echo-server
          image: echosvr:dev
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: test1
              value: old

---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  selector:
    app.kubernetes.io/name: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  # each key is a deployment name
  # value is a JSON array of {name, value} object
  echo-server: |
    [
      {
        "name": "test1",
        "value": "new1"
      },
      {
        "name": "test2",
        "value": "new2"
      }
    ]
