# permissions for end users to edit envvars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: envvar-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator-env-vars
    app.kubernetes.io/part-of: k8s-operator-env-vars
    app.kubernetes.io/managed-by: kustomize
  name: envvar-editor-role
rules:
- apiGroups:
  - custom.pedro
  resources:
  - envvars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom.pedro
  resources:
  - envvars/status
  verbs:
  - get
